### ISSUE TITLE
Set source at runtime does not work anymore

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Tilia.Trackers.ColliderFollower.Unity#117]
### Environment

[v2.0.7](https://github.com/ExtendRealityLtd/Tilia.Trackers.ColliderFollower.Unity/tree/v2.0.7)

### Steps to reproduce

1. Create Cube and place it at (-2,0,0). Remove its box collider.
2. Drag Trackers.ColliderFollower prefab into scene at (0,0,0).
3. Drag Cube as Source of collider follower.
4. Play scene, confirm that the collider follow the cube position.

![image](https://user-images.githubusercontent.com/22952143/172047061-9ecf7272-6ab6-4678-9de9-1f1c0cc33668.png)
5. Stop scene. Clear the Source of collider follower.
6. Deactivate the collider follower.
7. Create a BehaviourEnabledObserver and set up the events:
Activate collider follower
Set Cube as source of collider follower
call SnapToSource

### Expected behavior

Set the Cube as source in runtime should make the collider follow the cube just like it is set up in editor time.

### Current behavior

The collider is not following the Cube. In particular, the Object Follower's Source list does not contain the Cube.
![image](https://user-images.githubusercontent.com/22952143/172047217-1b3f5a91-90f8-4424-9d22-7e827390ae02.png)

**Comment by thestonefox** [comment]
Ok so the issue here is a race condition because the collider follower is disabled by default.

What is happening is...

you are enabling the tracker, on enable it tries to set source to `null` because it has no source. but then as soon as it becomes active it tries to set source to `cube` but then the `null` gets set afterwards (from the OnEnable call)

As property setters are not affected by state, you should set the source before activating the gameobject:

![image](https://user-images.githubusercontent.com/1029673/172048983-955cd861-0934-4a29-899c-ea2952b405b9.png)

**Comment by thestonefox** [comment]
So the chain of events are:

`GameObject.SetActive` is calling 

```
protected virtual void OnEnable()
{
    SetSource(Facade.Source);
}
```

Facade.Source is currently `null`

`OnEnable` is queued up to run at the end of the frame as it will continue to run the `ActiveAndEnabled` events

The next event of `SetSource` then runs, which will do this:

```
public virtual void SetSource(GameObject source)
{
    ObjectFollower.Sources.RunWhenActiveAndEnabled(() => ObjectFollower.Sources.Clear());
    ObjectFollower.Sources.RunWhenActiveAndEnabled(() => ObjectFollower.Sources.Add(source));
    PositionExtractor.Source = source;
}
```

This is waiting for the `ObjectFollower.Sources` ObservableList to become active and set the source... This is happening before the original `OnEnable` has even been processed.

So now your `Source` is set to `Cube` correctly.

but then at the end of the frame `OnEnable` sets source back to `null`

**Comment by fight4dream** [comment]
confirmed the reordering of event works
